## Preprocessing

In [31]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [32]:
# Drop the non-beneficial ID columns, 'EIN'.
application_df=application_df.drop(columns=["EIN"])

In [33]:
name_count = application_df.NAME.value_counts()
name_count

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [35]:
# Choose a cutoff value and create a list of names to be replaced
# use the variable name `names_to_replace`
names_to_replace = name_count[name_count<100].index

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 25987
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
HONOR SOCIETY OF PHI KAPPA PHI                                          107
MONTANA 4-H FOUNDATION INC                                              107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
Name: NAME, dtype: int64

In [36]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                        31
APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [37]:
# Look at APPLICATION_TYPE value counts for binning
app_count = application_df.APPLICATION_TYPE.value_counts()
app_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [38]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = app_count[app_count<500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(name,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [39]:
# Look at CLASSIFICATION value counts for binning
class_count=application_df.CLASSIFICATION.value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [40]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_count[class_count>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [41]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace=class_count[class_count<1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [42]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CIVITAN INTERNATIONAL,NAME_DEMOLAY INTERNATIONAL,NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA,NAME_HABITAT FOR HUMANITY INTERNATIONAL INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [43]:
# Split our preprocessed data into our features and target arrays
y = dummies_df.IS_SUCCESSFUL
X = dummies_df.drop('IS_SUCCESSFUL',1)

# Split the preprocessed data into a training and testing dataset
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

<ipython-input-43-6fc1d9dd75da>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = dummies_df.drop('IS_SUCCESSFUL',1)

In [44]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [45]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
n_features = len(X_train.values[0])
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80,input_dim=n_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                6640

 dense_4 (Dense)             (None, 30)                2430

 dense_5 (Dense)             (None, 1)                 31

=================================================================
Total params: 9101 (35.55 KB)
Trainable params: 9101 (35.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [46]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [47]:
# Train the model
fitted_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5126 - accuracy: 0.7455
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4930 - accuracy: 0.7568
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4910 - accuracy: 0.7585
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4885 - accuracy: 0.7584
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4873 - accuracy: 0.7593
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4861 - accuracy: 0.7604
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4853 - accuracy: 0.7608
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4842 - accuracy: 0.7631
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4836 - accuracy: 0.7624
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4833 - accuracy: 0.7619
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4829 - accuracy: 0.7631
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4817 - accuracy: 0.7633
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4814 - accuracy: 0.7636
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4810 - accuracy: 0.7629
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4810 - accuracy: 0.7639
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4802 - accuracy: 0.7621
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4800 - accuracy: 0.7638
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4794 - accuracy: 0.7647
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4797 - accuracy: 0.7645
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4791 - accuracy: 0.7657
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4787 - accuracy: 0.7645
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4787 - accuracy: 0.7640
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4783 - accuracy: 0.7651
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4778 - accuracy: 0.7646
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4779 - accuracy: 0.7640
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4779 - accuracy: 0.7655
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4774 - accuracy: 0.7650
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4766 - accuracy: 0.7654
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4771 - accuracy: 0.7656
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4764 - accuracy: 0.7647
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4759 - accuracy: 0.7659
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4766 - accuracy: 0.7662
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4759 - accuracy: 0.7661
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4757 - accuracy: 0.7671
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4755 - accuracy: 0.7668
Epoch 36/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4753 - accuracy: 0.7666
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4753 - accuracy: 0.7669
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4754 - accuracy: 0.7661
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4749 - accuracy: 0.7655
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4749 - accuracy: 0.7682
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4748 - accuracy: 0.7670
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4745 - accuracy: 0.7673
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4747 - accuracy: 0.7668
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4742 - accuracy: 0.7681
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4746 - accuracy: 0.7665
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4740 - accuracy: 0.7668
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4742 - accuracy: 0.7664
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4740 - accuracy: 0.7676
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4741 - accuracy: 0.7674
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4735 - accuracy: 0.7668
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4734 - accuracy: 0.7678
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4734 - accuracy: 0.7674
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4733 - accuracy: 0.7676
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4733 - accuracy: 0.7671
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4731 - accuracy: 0.7679
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4733 - accuracy: 0.7679
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4729 - accuracy: 0.7682
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4735 - accuracy: 0.7681
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4732 - accuracy: 0.7662
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4725 - accuracy: 0.7672
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4728 - accuracy: 0.7675
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7687
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4731 - accuracy: 0.7666
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4722 - accuracy: 0.7666
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4724 - accuracy: 0.7687
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4724 - accuracy: 0.7671
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4718 - accuracy: 0.7669
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4721 - accuracy: 0.7677
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4721 - accuracy: 0.7676
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4723 - accuracy: 0.7692
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4721 - accuracy: 0.7678
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4719 - accuracy: 0.7678
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4715 - accuracy: 0.7681
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4718 - accuracy: 0.7682
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7673
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7687
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4715 - accuracy: 0.7680
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4715 - accuracy: 0.7683
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4714 - accuracy: 0.7678
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4715 - accuracy: 0.7683
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7681
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7683
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7694
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7687
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7669
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4708 - accuracy: 0.7680
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4714 - accuracy: 0.7692
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4709 - accuracy: 0.7683
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4709 - accuracy: 0.7668
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4706 - accuracy: 0.7692
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4706 - accuracy: 0.7696
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4709 - accuracy: 0.7687
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4707 - accuracy: 0.7687
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4706 - accuracy: 0.7687
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4704 - accuracy: 0.7692
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4705 - accuracy: 0.7701
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4705 - accuracy: 0.7691
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4703 - accuracy: 0.7688
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4709 - accuracy: 0.7680
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4707 - accuracy: 0.7689

In [48]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5071 - accuracy: 0.7546 - 450ms/epoch - 2ms/step
Loss: 0.5070707201957703, Accuracy: 0.7546355724334717

In [49]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(