## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN'.
application_df=application_df.drop(columns=["EIN"])

In [3]:
name_count = application_df.NAME.value_counts()
name_count

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [4]:
# Choose a cutoff value and create a list of names to be replaced
# use the variable name `names_to_replace`
names_to_replace = name_count[name_count<100].index

# Replace in dataframe
for name in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(name,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 25987
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
HONOR SOCIETY OF PHI KAPPA PHI                                          107
MONTANA 4-H FOUNDATION INC                                              107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
Name: NAME, dtype: int64

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                        31
APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts for binning
app_count = application_df.APPLICATION_TYPE.value_counts()
app_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = app_count[app_count<500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Look at CLASSIFICATION value counts for binning
class_count=application_df.CLASSIFICATION.value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_count[class_count>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace=class_count[class_count<1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CIVITAN INTERNATIONAL,NAME_DEMOLAY INTERNATIONAL,NAME_FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA,NAME_HABITAT FOR HUMANITY INTERNATIONAL INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [12]:
# Split our preprocessed data into our features and target arrays
y = dummies_df.IS_SUCCESSFUL
X = dummies_df.drop('IS_SUCCESSFUL',1)

# Split the preprocessed data into a training and testing dataset
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

<ipython-input-12-6fc1d9dd75da>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = dummies_df.drop('IS_SUCCESSFUL',1)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
n_features = len(X_train.values[0])
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80,input_dim=n_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                6000

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 8461 (33.05 KB)
Trainable params: 8461 (33.05 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model
fitted_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5151 - accuracy: 0.7424
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4950 - accuracy: 0.7544
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4916 - accuracy: 0.7562
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4904 - accuracy: 0.7589
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4883 - accuracy: 0.7590
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4870 - accuracy: 0.7593
Epoch 7/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4860 - accuracy: 0.7598
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4855 - accuracy: 0.7605
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4846 - accuracy: 0.7616
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4839 - accuracy: 0.7626
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4837 - accuracy: 0.7617
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4827 - accuracy: 0.7632
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4820 - accuracy: 0.7629
Epoch 14/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4821 - accuracy: 0.7624
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4816 - accuracy: 0.7624
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4809 - accuracy: 0.7616
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4812 - accuracy: 0.7629
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4803 - accuracy: 0.7643
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4803 - accuracy: 0.7643
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4800 - accuracy: 0.7643
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4796 - accuracy: 0.7650
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4793 - accuracy: 0.7645
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4791 - accuracy: 0.7651
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4784 - accuracy: 0.7632
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4783 - accuracy: 0.7651
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4786 - accuracy: 0.7655
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4781 - accuracy: 0.7649
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4781 - accuracy: 0.7653
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4774 - accuracy: 0.7655
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4776 - accuracy: 0.7644
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4770 - accuracy: 0.7664
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4772 - accuracy: 0.7655
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4768 - accuracy: 0.7663
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4768 - accuracy: 0.7650
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4769 - accuracy: 0.7645
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4764 - accuracy: 0.7650
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4764 - accuracy: 0.7651
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4759 - accuracy: 0.7652
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4758 - accuracy: 0.7660
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4759 - accuracy: 0.7663
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4757 - accuracy: 0.7671
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4756 - accuracy: 0.7659
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4752 - accuracy: 0.7666
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4753 - accuracy: 0.7676
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4748 - accuracy: 0.7676
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4751 - accuracy: 0.7669
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4750 - accuracy: 0.7660
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4746 - accuracy: 0.7666
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4746 - accuracy: 0.7678
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4746 - accuracy: 0.7660
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4745 - accuracy: 0.7663
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4746 - accuracy: 0.7664
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4743 - accuracy: 0.7664
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4740 - accuracy: 0.7671
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4740 - accuracy: 0.7675
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4737 - accuracy: 0.7670
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4736 - accuracy: 0.7675
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4738 - accuracy: 0.7666
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4737 - accuracy: 0.7678
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4733 - accuracy: 0.7678
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4737 - accuracy: 0.7677
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4734 - accuracy: 0.7676
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4732 - accuracy: 0.7683
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4731 - accuracy: 0.7683
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4735 - accuracy: 0.7682
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4733 - accuracy: 0.7683
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4728 - accuracy: 0.7683
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4724 - accuracy: 0.7677
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4729 - accuracy: 0.7671
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4729 - accuracy: 0.7677
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4723 - accuracy: 0.7684
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4729 - accuracy: 0.7677
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4722 - accuracy: 0.7685
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7686
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4722 - accuracy: 0.7678
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7691
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4722 - accuracy: 0.7683
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4722 - accuracy: 0.7680
Epoch 79/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4721 - accuracy: 0.7684
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4723 - accuracy: 0.7676
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4719 - accuracy: 0.7681
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4719 - accuracy: 0.7685
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4720 - accuracy: 0.7684
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4717 - accuracy: 0.7682
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4719 - accuracy: 0.7689
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4715 - accuracy: 0.7682
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4718 - accuracy: 0.7680
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4717 - accuracy: 0.7687
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7682
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7684
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7680
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7685
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7685
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4709 - accuracy: 0.7693
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4706 - accuracy: 0.7677
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4711 - accuracy: 0.7684
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4712 - accuracy: 0.7687
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4714 - accuracy: 0.7693
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4711 - accuracy: 0.7686
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4709 - accuracy: 0.7692

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5030 - accuracy: 0.7549 - 501ms/epoch - 2ms/step
Loss: 0.5029809474945068, Accuracy: 0.7548688054084778

In [18]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

# **Analysis Report**
## Overview
The purpose of this analysis was to see which organizations would be successful if funded by Alphabet Soup.
## Results
### Data Preprocessing

*   The targets for our model were the values in the "IS_SUCCESSFUL" column of the dataframe.
*   The features are the remaining columns in the dataset.
* The variables in the "EIN" and "NAME" columns were originally removed from the dataset because they were neither features nor targets for the model.


### Compiling, Training, and Evaluating the Model
* I used two hidden layers for the model, with one output layer. The ReLU activaction function was used for the hidden layers, and the sigmoid function was used for the output layer. ReLU is commonly used in hidden layers for neural networks, and Sigmoid is used in the output layer for binary classification, which was used in our model. 80 neurons were selected for the first hidden layer, 30 for the second, and 1 for the output layer.
* The model got very close to target model performance the first time, with 73% accuracy, but was not quite there yet.
* To opmtimize model peformance, I simply put the "NAME" column back in the dataset to use as a feature, and replaced every value with a count of less than 100 with "Other." After which the model was able to achieve and accuracy of 75%.

## Summary
Overall, the model performed fairly well, but could definitely be more accurate. There was also a loss of about 50%. To fix these problems, we possibly could have created a model with different features. We removed some, but maybe adding others, or removing even more features could have improved the model's performance. We also could have used more or less epochs when fitting the model to see what effect that would have on the performance. Overall, I do not think I would reccommend this model because even though its performance is passible, I believe there is still too much room for error.